package com.pause.app.service.overlay

enum class OverlayState {
    IDLE,
    SHOWING_DELAY,
    SHOWING_LAUNCH_LIMIT,
    SHOWING_ALLOWANCE_REACHED,
    SHOWING_COOLDOWN,
    SHOWING_REFLECTION,
    SHOWING_COMMITMENT_BLOCK,
    SHOWING_LOCK_INTERVENTION,
    SHOWING_STRICT_BLOCK,
    SHOWING_POWER_BLOCK,
    SHOWING_SESSION_RESUME,
    SHOWING_SESSION_COMPLETE,
    SHOWING_EMERGENCY_CONFIRM,
    SHOWING_PARENTAL_BLOCK,
    SHOWING_PIN_ENTRY,
    SHOWING_SCHEDULE_RESUME
}
