package com.pause.app.service.overlay

enum class OverlayState(val priority: Int) {
    IDLE(0),
    SHOWING_SCHEDULE_RESUME(10),
    SHOWING_SESSION_RESUME(10),
    SHOWING_SESSION_COMPLETE(10),
    SHOWING_LOCK_INTERVENTION(10),
    SHOWING_REFLECTION(30),
    SHOWING_DELAY(40),
    SHOWING_COOLDOWN(70),
    SHOWING_LAUNCH_LIMIT(75),
    SHOWING_ALLOWANCE_REACHED(80),
    SHOWING_COMMITMENT_BLOCK(80),
    SHOWING_PARENTAL_BLOCK(90),
    SHOWING_POWER_BLOCK(90),
    SHOWING_PIN_ENTRY(95),
    SHOWING_EMERGENCY_CONFIRM(95),
    SHOWING_STRICT_BLOCK(100),
}
